services:
  wp:
    environment:
      LIBOPS_SMTP_HOST: mailpit
      LIBOPS_SMTP_PORT: "1025"
    volumes:
      - ./web/app/mu-plugins:/var/www/bedrock/web/app/mu-plugins:z,rw
      - ./web/app/plugins:/var/www/bedrock/web/app/plugins:z,rw
      - ./web/app/themes:/var/www/bedrock/web/app/themes:z,rw
  mariadb:
    ports:
      - "3306:3306"
  mailpit:
    image: axllent/mailpit:v1.31@sha256:c96991d9bef73594c246d89ca81411d4e916f03e76a7d2d72fa2ab5dd3c9ce24
    ports:
      - "1025:1025"
      - "8025:8025"
