services:
  wp:
    environment:
      LIBOPS_SMTP_HOST: mailpit
      LIBOPS_SMTP_PORT: "1025"
    volumes:
      - ./web/app/mu-plugins:/var/www/bedrock/web/app/mu-plugins:z,rw
      - ./web/app/plugins:/var/www/bedrock/web/app/plugins:z,rw
      - ./web/app/themes:/var/www/bedrock/web/app/themes:z,rw
  mariadb:
    ports:
      - "3306:3306"
  mailpit:
    image: axllent/mailpit:v1.31@sha256:98b916bd3c8d61f7633a52d3ea2f58d00620cb01ca57ab59edde68c347a95365
    ports:
      - "1025:1025"
      - "8025:8025"
