services:
  wp:
    environment:
      LIBOPS_SMTP_HOST: mailpit
      LIBOPS_SMTP_PORT: "1025"
    volumes:
      - ./web/app/plugins:/var/www/bedrock/web/app/plugins:rw
      - ./web/app/themes:/var/www/bedrock/web/app/themes:rw
  mariadb:
    ports:
      - 3306:3306
  mailpit:
    image: axllent/mailpit:v1.26
    ports:
      - 1025:1025
      - 8025:8025
