#!/command/with-contenv bash

DIRS=(
  /var/www/bedrock/web/app/uploads
)
echo "Setting WordPress upload permissions..."
for DIR in "${DIRS[@]}"; do
  mkdir -p "$DIR"
  chown -R nginx:nginx "$DIR"
  find "$DIR" -type d -exec chmod 750 {} \;
  find "$DIR" -type f -exec chmod 640 {} \;
done
echo "WordPress upload permissions set: dirs=750, files=640"
