name: lint-test
on:
  push:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0

      - run: make lint

      - run: make test

  build-push:
    needs: [lint-test]
    uses: libops/.github/.github/workflows/build-push-ghcr.yaml@d7f0ba06b4c8a1f8559892ea65a0b1af4d024dd3 # main
    permissions:
      contents: read
      packages: write
    secrets: inherit
